In [1]:
#1.
import numpy as np

In [2]:
#2.
print(np.__version__)

1.15.4


In [3]:
#3.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#4.
data1=np.zeros(5)
size=data1.size*data1.itemsize
print("%d bytes"% size)

40 bytes


In [13]:
#5.如何从命令行得到numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [14]:
#6.
data2=np.zeros(10)
data2[4]=1
print(data2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#7.
data3=np.arange(10,50)
print(data3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
#8.
data4=data3[::-1]
print(data4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [18]:
#9.
data5=np.arange(0,9)
data5=data5.reshape(3,3)
print(data5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#10.(newlearn)
n=np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4], dtype=int64),)


In [21]:
#11.
data6=np.eye(3)
print(data6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#12.
data7=np.random.random((3,3,3))
print(data7)

[[[0.13455459 0.26601423 0.68338627]
  [0.84296493 0.40845445 0.53320935]
  [0.85677201 0.73128091 0.84107011]]

 [[0.66634265 0.32490184 0.07485934]
  [0.63276252 0.95082833 0.5601329 ]
  [0.24580891 0.37716351 0.57087125]]

 [[0.88677498 0.29269168 0.30356327]
  [0.37320713 0.94115078 0.13015423]
  [0.56697642 0.65846749 0.3745454 ]]]


In [23]:
#13.
data8=np.random.random((10,10))
data8_min=data8.min()
data8_max=data8.max()
print(data8_min)
print(data8_max)

0.009648932344953676
0.9834223509228069


In [24]:
#14.注意随机数组和随机向量创建方法的不同处
data9=np.random.random(30)
data9_mean=data9.mean()
print(data9_mean)

0.5218968087765166


In [25]:
#15.注意固定边界值的创建方法
data10=np.ones((5,5))
data10[1:-1,1:-1]=0
print(data10)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
#16.***用任意值填充为边界值
data11=np.pad(data8,pad_width=1,mode='constant',constant_values=0)
print(data11)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.36255051 0.55511915 0.13886867 0.39050554 0.25467782
  0.83551539 0.51203484 0.2934236  0.36966173 0.12706039 0.        ]
 [0.         0.49562416 0.         0.         0.         0.
  0.         0.         0.         0.         0.94597605 0.        ]
 [0.         0.71638963 0.         0.         0.         0.
  0.         0.         0.         0.         0.4804004  0.        ]
 [0.         0.94029556 0.         0.         0.         0.
  0.         0.         0.         0.         0.79878385 0.        ]
 [0.         0.45592474 0.         0.         0.         0.
  0.         0.         0.         0.         0.63226258 0.        ]
 [0.         0.13137185 0.         0.         0.         0.
  0.         0.         0.         0.         0.27864046 0.        ]
 [0.         0.23410832 0.         0.         0.         0.
  0.         0.         0.   

In [31]:
#17.
data12=np.nan
print(data12)
print(0*np.nan)
print(np.nan==np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
nan
False
nan
False


In [42]:
#18.创建一个5×5的矩阵，并设置值1，2，3，4落在其对角线下方位置
data13=np.diag(1+np.arange(4),k=-1)  ##这里k=-1,相当于对角线的值向下平移一个单位
print(data13)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


In [43]:
#19.棋盘式
data14=np.zeros((8,8),dtype=int)
data14[1::2,::2]=1
data14[::2,1::2]=1
print(data14)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [49]:
#20.
data15=np.random.random((6,7,8))
print(data15)
print(np.unravel_index(10,(6,7,8)))

[[[0.25018874 0.33379644 0.83755824 0.48734996 0.3915661  0.83461859
   0.29223303 0.51730457]
  [0.12596339 0.52308934 0.74317046 0.1551165  0.88709504 0.90643458
   0.38767098 0.87948404]
  [0.63820228 0.39085573 0.51747634 0.74894126 0.14730229 0.01703075
   0.9923503  0.08493355]
  [0.85730174 0.10527474 0.99345966 0.07988152 0.91966919 0.97527711
   0.40014799 0.5128055 ]
  [0.48717051 0.85144022 0.3625538  0.43465606 0.72131823 0.61678444
   0.32629598 0.03568227]
  [0.45348571 0.42974505 0.76362794 0.42527989 0.61363871 0.36918426
   0.55761517 0.28724344]
  [0.5747601  0.17036704 0.30663763 0.90598017 0.72515339 0.33305452
   0.19947907 0.40790611]]

 [[0.20999841 0.0600704  0.73708741 0.63645112 0.88433304 0.2827184
   0.60676529 0.4927445 ]
  [0.7438615  0.54689014 0.71479694 0.38174675 0.98492837 0.35138497
   0.3575115  0.42796091]
  [0.28793041 0.04384411 0.42109447 0.07084352 0.98220334 0.15634272
   0.78641792 0.95976067]
  [0.28122332 0.91836827 0.83384263 0.45469671 0.

In [50]:
#21.用tile函数去创建一个8×8的棋盘样式矩阵（注：tile函数是指将原矩阵横向、纵向地复制）
data16=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(data16)
                         

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
#22.归一化(数据处理中蛮重要)
data17=np.random.random((5,5))
data17_min,data17_max=data17.min(),data17.max()
data17_normal=(data17-data17_min)/(data17_max-data17_min)
print(data17_normal)

[[0.0860784  0.7006751  0.64499103 0.43943364 0.17888106]
 [0.         0.43299704 0.39961644 0.89272116 0.77559779]
 [0.66803238 0.05571809 0.10455027 0.2082419  0.82387404]
 [0.29711512 0.80971865 0.92611564 0.9647303  0.55332263]
 [1.         0.27249215 0.88095103 0.63542681 0.48374521]]


In [53]:
#23.创建一个将颜色描述为RGBA四个无符号字节地自定义dtype
color=np.dtype([('R',np.ubyte,1),
               ('G',np.ubyte,1),
               ('B',np.ubyte,1),
               ('A',np.ubyte,1)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [55]:
#24.两矩阵相乘(点乘)
matrix1=np.arange(1,16).reshape(5,3)
print(matrix1)
matrix2=np.arange(7,13).reshape(3,2)
matrix=np.dot(matrix1,matrix2)
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 58  64]
 [139 154]
 [220 244]
 [301 334]
 [382 424]]


In [58]:
#25. 给定一个一位数组，对其在3到8间地所有元素取反
data18=np.arange(1,10)
data18[(3<=data18)&(data18<=8)]*=-1
print(data18)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


In [67]:
#26.(不太懂)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [74]:
#27.
data18=np.arange(3)
print(data18**data18)
print(2<<data18>>2)
print(data18<-data18)
print(1j*data18)
print(data18/1/1)
print(data18<data18>data18)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
#28.
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array[np.nan]).astype(int).astype(float)

nan
0


C:\Users\hyvto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\hyvto\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


TypeError: 'builtin_function_or_method' object is not subscriptable

In [80]:
#29.如何从零位对浮点数组做舍入(有点儿复杂)
data=np.random.uniform(-10,+10,10)
print(data)
print(np.copysign(np.ceil(np.abs(data)),data))

[ 9.44066368 -8.82846459 -2.95342445 -4.17684084 -8.48899831 -1.30710266
  4.63977388 -3.94315515 -1.87534229  6.12184355]
[10. -9. -3. -5. -9. -2.  5. -4. -2.  7.]


In [82]:
#30.找寻两数组中相同地元素
data1=np.arange(1,10)
data2=np.arange(6,15)
data=np.intersect1d(data1,data2)
print(data)

[6 7 8 9]


In [83]:
#31.忽略numpy地所有警告（不建议使用）
defaults=np.seterr(all='ignore')
data=np.zeros(5)/0
_=np.seterr(**defaults)




In [84]:
#32.
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


C:\Users\hyvto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [88]:
#33.如何得到昨天，今天和明天的日期
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('yesterday is '+str(yesterday))
print('toady is '+str(today))
print('tomorrow is '+str(tomorrow))


yesterday is 2019-08-06
toady is 2019-08-07
tomorrow is 2019-08-08


In [89]:
#34.如何得到所有与2016年7月相对应的日期
data=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(data)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [92]:
#35.(不太懂)
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [102]:
#36.5中方法取整
data=np.random.uniform(0,10,10)
print(data)
print(data-data%1)
print(np.trunc(data))
print(np.floor(data))
print(np.ceil(data)-1)
print(data.astype(int))

[4.74448672 6.02543567 4.82131246 6.22181731 9.15608725 6.50188013
 4.1838723  6.4924192  7.2245871  7.03283583]
[4. 6. 4. 6. 9. 6. 4. 6. 7. 7.]
[4. 6. 4. 6. 9. 6. 4. 6. 7. 7.]
[4. 6. 4. 6. 9. 6. 4. 6. 7. 7.]
[4. 6. 4. 6. 9. 6. 4. 6. 7. 7.]
[4 6 4 6 9 6 4 6 7 7]


In [103]:
#37.
data=np.zeros((5,5))
data+=np.arange(0,5)
print(data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [106]:
#38.通过考虑一个可以生成10个整数的函数来构建一个数组
def generate():
    for x in range(0,10):
        yield x
data=np.fromiter(generate(),dtype=float,count=-1)
print(data)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [118]:
#39. 
data=np.linspace(0,1,11,endpoint=False)[1:]
print(data)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [117]:
#40.
data=np.random.random(10)
print(data)
data.sort()
print(data)

[0.90366214 0.53182079 0.45162613 0.00764868 0.32316966 0.78769615
 0.93363483 0.55792481 0.22962265 0.182664  ]
[0.00764868 0.182664   0.22962265 0.32316966 0.45162613 0.53182079
 0.55792481 0.78769615 0.90366214 0.93363483]


In [119]:
#41.
data=np.arange(5)
np.add.reduce(data)

10

In [120]:
#42.判断两个随机数组是否相同
data1=np.random.random(5)
data2=np.random.random(5)
equal=np.allclose(data1,data2)
print(equal)

False


In [122]:
#43.创建一个只读数组
data=np.arange(5)
data.flags.writeable=False

In [123]:
#44.将笛卡尔坐标下的一个据真转化为极坐标形式(不太懂)
data=np.random.random((10,2))
X,Y=data[:0],data[:1]
R=np.sqrt(X**2+Y**2)
T=np.arctan(2)
print(R)
print(T)

[]
1.1071487177940904


In [126]:
#45.将一数组中的最大值替换为0
data=np.arange(1,10)
data[data.argmax()]=0
print(data)

[1 2 3 4 5 6 7 8 0]


In [127]:
#46.(不懂）)
data = np.zeros((5,5), [('x',float),('y',float)])
data['x'], data['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(data)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [129]:
#47.
data=np.arange(5)
data0=data+0.5
data1=1.0/np.subtract.outer(data,data0)
print(np.linalg.det(data1))

-131.91659501325745


In [131]:
#48.
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [132]:
#49.
np.set_printoptions(threshold=np.nan)
data=np.zeros((8,8))
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [135]:
#50.
data=np.arange(10)
v=np.random.uniform(0,100)
index=(np.abs(data-v)).argmin()
print(index)


5


In [136]:
#51.
data=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(data)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
