In [2]:
import pandas as pd 
import numpy as np

In [8]:
###层次化索引
#层次化索引是pandas的一项重要功能，它使你可以在一个轴上拥有多个索引级别。可以使你能以低维度式处理高维度的数据
data=pd.Series(np.random.randn(6),index=[['a','a','b','b','c','c'],[1,2,3,1,2,4]])
print(data)
print(data.index)
print(data['b'])
print(data['b':'c'])
print(data.loc[['b','d']])
print(data[:,2])

a  1   -1.052055
   2    0.919994
b  3   -0.373836
   1    0.722339
c  2    0.648154
   4   -0.234305
dtype: float64
MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3, 4]],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 2, 0, 1, 3]])
3   -0.373836
1    0.722339
dtype: float64
b  3   -0.373836
   1    0.722339
c  2    0.648154
   4   -0.234305
dtype: float64
b  3   -0.373836
   1    0.722339
dtype: float64
a    0.919994
c    0.648154
dtype: float64


In [12]:
#层次索引在数据重塑和基于分组的操作（入生成透视表）中扮演着重要的角色，例如:通过unstack方法可以将数据重新安排到一个dataframe中
data.unstack() #stack  将数据的列“旋转”为行  unstack  将数据的行“旋转”为列
data.unstack().stack()

a  1   -1.052055
   2    0.919994
b  1    0.722339
   3   -0.373836
c  2    0.648154
   4   -0.234305
dtype: float64

In [16]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])
print(frame)
frame.index.names=['key1','key2']
frame.columns.names=['state','color']
print(frame)
frame['Ohio']

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11
state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11


color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [21]:
###重排与分级排序
frame.swaplevel('key1','key2')  ##swaplevel接受两个级别编号或名称，并返回一个互换了级别的新对象
frame.sort_index(level=1)
frame.swaplevel(0,1).sort_index(level=0)
frame.sum(level='key2')
frame.sum(level='color',axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [27]:
df1=pd.DataFrame({'key':['a','b','b','d'],'data1':range(4)})
df2=pd.DataFrame({'key':['a','b','d'],'data2':range(3)})
print(df1)
print(df2)
data=pd.merge(df1,df2)
print(data)

  key  data1
0   a      0
1   b      1
2   b      2
3   d      3
  key  data2
0   a      0
1   b      1
2   d      2
  key  data1  data2
0   a      0      0
1   b      1      1
2   b      2      1
3   d      3      2


In [14]:
df3=pd.DataFrame({'1key':['b','a','c'],'data':range(3)})
df4=pd.DataFrame({'ykey':['a','c','f'],'data2':range(3)})
pd.merge(df3,df4,left_on='1key',right_on='ykey')
print(pd.merge(df1,df2,how='outer'))
#####说明：merge做的是"内连接";结果中的键是交集，其他方式还有"left","right"以及"outer"。外连接求取的是键的并集，组合了左连接和右连接的效果。
#inner使用两个表都有的键，left使用左表中所有的键;right使用右表中所有的键;outer使用两表中所有的键
print(df3.join(df4,how='outer')) ##join能更为方便地实现按索引合并，join方法默认使用地是左连接，保留左边表地行索引。

  key  data1  data2
0   a      0      0
1   b      1      1
2   b      2      1
3   d      3      2
  1key  data ykey  data2
0    b     0    a      0
1    a     1    c      1
2    c     2    f      2


In [18]:
###轴向连接
#另一种数据合并运算也被称作连接（concatenation），绑定(binding),或堆叠（stacking）。numpy中地concatentaion函数可以用Numpy数组来做。
arr=np.arange(12).reshape((3,4))
print(arr)
print(np.concatenate([arr,arr],axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [21]:
s1=pd.Series([0,1],index=['a','b'])
s2=pd.Series([2,3,4],index=['c','d','e'])
s3=pd.Series([5,6],index=['f','g'])
pd.concat([s1,s2,s3])  ##concat默认的是axis=0
##当axis=1时，就会生成一个dataframe
print(pd.concat([s1,s2,s3],axis=1))
print(pd.concat([s1,s2,s3],axis=1,join='inner'))

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0
Empty DataFrame
Columns: [0, 1, 2]
Index: []


C:\Users\hyvto\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [26]:
df1=pd.DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])
df2=pd.DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])
df1
df2
pd.concat([df1,df2],axis=1,keys=['level1','level2'])
pd.concat({'level1':df1,'level2':df2},axis=1)

C:\Users\hyvto\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """
C:\Users\hyvto\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [27]:
###8.3 重塑和轴向旋转 （reshape和pivot）
##unstack 和stack（前面）


In [28]:
###将长格式旋转为宽格式,对于时间序列的处理


FileNotFoundError: [Errno 2] File b'example/macrodata.csv' does not exist: b'example/macrodata.csv'